# Generated by Django 4.2.11 on 2024-05-11 12:38

import builtins
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('makeup', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=350)),
                ('housenumber', models.IntegerField()),
                ('postalcode', models.IntegerField()),
                ('paymentmethod', models.CharField(max_length=1000)),
                ('sendingtime', models.CharField(max_length=1000)),
                ('receivername', models.CharField(max_length=25)),
            ],
            options={
                'verbose_name': 'فروش',
            },
        ),
        migrations.AlterModelOptions(
            name='makeup',
            options={'verbose_name': 'لوازم آرایشی'},
        ),
        migrations.AlterModelOptions(
            name='shop',
            options={'verbose_name': 'فروشگاه'},
        ),
        migrations.AlterModelOptions(
            name='skincare',
            options={'verbose_name': 'لوازم مراقبت پوستی'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'کاربر'},
        ),
        migrations.AlterField(
            model_name='makeup',
            name='price',
            field=models.CharField(max_length=7),
        ),
        migrations.AlterField(
            model_name='makeup',
            name='remained',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='shop',
            name='shopphonenumber',
            field=models.CharField(max_length=11),
        ),
        migrations.AlterField(
            model_name='skincare',
            name='price',
            field=models.CharField(max_length=7),
        ),
        migrations.AlterField(
            model_name='skincare',
            name='remained',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='user',
            name='nationalcode',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='userphonenumber',
            field=models.CharField(max_length=11),
        ),
        migrations.CreateModel(
            name='Digitalstuff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remained', models.CharField(max_length=3)),
                ('price', models.CharField(max_length=7)),
                ('maincategory', models.CharField(max_length=20)),
                ('brandname', models.CharField(max_length=20)),
                ('aboutproduct', models.TextField(max_length=350)),
                ('manufacturing_country', models.CharField(max_length=20)),
                ('warranty', models.IntegerField()),
                ('productname', models.ForeignKey(max_length=20, on_delete=builtins.any, to='makeup.shop')),
            ],
            options={
                'verbose_name': 'لوازم برقی',
            },
        ),
    ]
