# Generated by Django 4.2.11 on 2024-05-29 10:19

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('makeup', '0002_sell_alter_makeup_options_alter_shop_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='password',
            new_name='last_name',
        ),
        migrations.RemoveField(
            model_name='shop',
            name='shopphonenumber',
        ),
        migrations.RemoveField(
            model_name='user',
            name='address',
        ),
        migrations.RemoveField(
            model_name='user',
            name='gmail',
        ),
        migrations.RemoveField(
            model_name='user',
            name='lastname',
        ),
        migrations.RemoveField(
            model_name='user',
            name='nationalcode',
        ),
        migrations.RemoveField(
            model_name='user',
            name='userphonenumber',
        ),
        migrations.AddField(
            model_name='digitalstuff',
            name='shopname',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='makeup.shop'),
        ),
        migrations.AddField(
            model_name='makeup',
            name='shopname',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='makeup.shop'),
        ),
        migrations.AddField(
            model_name='skincare',
            name='shopname',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='makeup.shop'),
        ),
        migrations.AddField(
            model_name='user',
            name='email_address',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='national_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(default=True, max_length=15, validators=[django.core.validators.RegexValidator(message='Enter a valid phone number', regex='\\d{10,14}')]),
        ),
        migrations.AlterField(
            model_name='digitalstuff',
            name='productname',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='makeup',
            name='productname',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='shop',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='shop_images/'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='shopname',
            field=models.CharField(default=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='skincare',
            name='productname',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='age',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AddField(
            model_name='shop',
            name='shopPhoneNumber',
            field=models.CharField(default=True, max_length=15, validators=[django.core.validators.RegexValidator(message='Enter a valid phone number', regex='\\d{10,14}')]),
        ),
    ]
