# Generated by Django 4.2.11 on 2024-06-28 18:10

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('makeup', '0003_rename_password_user_last_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('commenttext', models.TextField(max_length=250)),
            ],
        ),
        migrations.AddField(
            model_name='shop',
            name='city',
            field=models.CharField(default='iran', max_length=16),
        ),
        migrations.AlterField(
            model_name='digitalstuff',
            name='shopname',
            field=models.ForeignKey(default='shop', on_delete=django.db.models.deletion.CASCADE, to='makeup.shop'),
        ),
        migrations.AlterField(
            model_name='makeup',
            name='shopname',
            field=models.ForeignKey(default='shop', on_delete=django.db.models.deletion.CASCADE, to='makeup.shop'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='shopPhoneNumber',
            field=models.CharField(default='09123456789', max_length=15, validators=[django.core.validators.RegexValidator(message='Enter a valid phone number', regex='\\d{10,14}')]),
        ),
        migrations.AlterField(
            model_name='shop',
            name='shopname',
            field=models.CharField(default='shop', max_length=50),
        ),
        migrations.AlterField(
            model_name='skincare',
            name='shopname',
            field=models.ForeignKey(default='shop', on_delete=django.db.models.deletion.CASCADE, to='makeup.shop'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(default='09123456789', max_length=15, validators=[django.core.validators.RegexValidator(message='Enter a valid phone number', regex='\\d{10,14}')]),
        ),
    ]
