# Generated by Django 4.2.11 on 2024-06-28 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('makeup', '0004_comment_shop_city_alter_digitalstuff_shopname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='digitalstuff',
            name='price',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
        migrations.AlterField(
            model_name='makeup',
            name='price',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
        migrations.AlterField(
            model_name='skincare',
            name='price',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
    ]
